# Generated by Django 5.1.4 on 2024-12-07 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_products_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='user_id',
            new_name='user',
        ),
    ]
