# Generated by Django 5.1.3 on 2024-11-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('accept', models.BooleanField(default=False)),
                ('addressee_products', models.ManyToManyField(related_name='addressee_products', to='items.products')),
                ('sender_item', models.ManyToManyField(related_name='sender_item', to='items.products')),
            ],
        ),
    ]
